name: Build + Publish Strapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Main Dependencies
        run: npm ci

      # Install and build each plugin
      - name: Install and Build Import-Data Plugin
        working-directory: src/plugins/import-data
        run: |
          npm install
          npm run build

      - name: Install and Build Yookassa-Payment Plugin
        working-directory: src/plugins/yookassa-payment
        run: |
          npm install
          npm run build

      - name: Build Strapi
        run: npm run build

      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: 'strapi-core'
          token: ${{ secrets.APP_TOKEN }}
          image: 'ghcr.io/aintnewtathis-yy/strapi-app:latest'
 